# Generated by Django 5.2.3 on 2025-06-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='cars',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='cars',
            index=models.Index(fields=['-time_create'], name='cars_cars_time_cr_4cf2ef_idx'),
        ),
    ]
