# Generated by Django 5.2.3 on 2025-06-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_cars_options_cars_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
