# Generated by Django 5.2.3 on 2025-06-22 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_category_cars_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.category'),
        ),
    ]
