# Generated by Django 5.2.3 on 2025-06-23 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_tagpost_cars_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='VinNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=17)),
            ],
        ),
        migrations.AddField(
            model_name='cars',
            name='vin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='car', to='cars.vinnumber'),
        ),
    ]
