# Generated by Django 5.2.3 on 2025-06-23 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_vinnumber_cars_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='vin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='car', to='cars.vinnumber'),
        ),
        migrations.AlterField(
            model_name='vinnumber',
            name='number',
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
