# Generated by Django 5.2.3 on 2025-06-28 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_alter_cars_vin'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads_model')),
            ],
        ),
        migrations.AlterModelOptions(
            name='cars',
            options={'ordering': ['-time_create'], 'verbose_name_plural': 'The most cheep cars '},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterField(
            model_name='cars',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='cars.category', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Country'),
        ),
    ]
